// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsFwz2rmCJ07w8x_jvu414pPlnDqp78nM',
    appId: '1:664280682142:web:c5c3b6eee676193efc358f',
    messagingSenderId: '664280682142',
    projectId: 'flutter-core-32a5b',
    authDomain: 'flutter-core-32a5b.firebaseapp.com',
    storageBucket: 'flutter-core-32a5b.firebasestorage.app',
    measurementId: 'G-BWJB39M31S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYbsZGtdnoKlh4j47K5mAi7Ou5CINokDw',
    appId: '1:664280682142:android:830fe892c914d908fc358f',
    messagingSenderId: '664280682142',
    projectId: 'flutter-core-32a5b',
    storageBucket: 'flutter-core-32a5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiseDoOjQkuZ5nVQPLOw1Txfu55lGlfcA',
    appId: '1:664280682142:ios:405ca336a505a3a0fc358f',
    messagingSenderId: '664280682142',
    projectId: 'flutter-core-32a5b',
    storageBucket: 'flutter-core-32a5b.firebasestorage.app',
    iosBundleId: 'com.example.flutterCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiseDoOjQkuZ5nVQPLOw1Txfu55lGlfcA',
    appId: '1:664280682142:ios:405ca336a505a3a0fc358f',
    messagingSenderId: '664280682142',
    projectId: 'flutter-core-32a5b',
    storageBucket: 'flutter-core-32a5b.firebasestorage.app',
    iosBundleId: 'com.example.flutterCore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsFwz2rmCJ07w8x_jvu414pPlnDqp78nM',
    appId: '1:664280682142:web:d1a415a0f6d5a369fc358f',
    messagingSenderId: '664280682142',
    projectId: 'flutter-core-32a5b',
    authDomain: 'flutter-core-32a5b.firebaseapp.com',
    storageBucket: 'flutter-core-32a5b.firebasestorage.app',
    measurementId: 'G-G9VP86X6Z9',
  );
}
