default_platform(:android)

platform :android do
  desc "Tự động Build APK và đẩy lên Firebase cho Tester"
  lane :distribute_to_qa do

    # 1. Build APK bằng Shorebird (cú pháp đúng)
    # - 'shorebird release android' sẽ build release APK
    # - Các flutter flag truyền sau '--' (dấu 2 gạch)
    sh("cd ../.. && shorebird release android -- --obfuscate --split-debug-info=build/app/outputs/symbols")

    # 2. Upload APK lên Firebase App Distribution
    firebase_app_distribution(
      app: "1:664280682142:android:68754f2ce19d627afc358f",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "trunghungpq456@gmail.com",
      release_notes: "Bản build tự động từ CI/CD!"
    )
  end
end