name: Distribute to Firebase QA

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      # 1. Lấy code về
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Cài đặt Java (Cần thiết để build Android)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Cài đặt Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      # 3.1 Cài đặt Shorebird CLI (Cần thiết cho Code Push)
      - name: Install Shorebird
        run: |
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          echo "$HOME/.shorebird/bin" >> $GITHUB_PATH
      # ========================================================
      # BƯỚC QUAN TRỌNG: TẠO FILE GOOGLE-SERVICES TỪ SECRET
      # ========================================================
      - name: 📝 Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json

      # 4. Cài đặt Ruby & Tự động chạy Bundle Install cho Fastlane
      - name: Setup Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: android

      # 5. Kích hoạt Fastlane
      - name: Build and Distribute APK
        working-directory: android
        env:
          # Token này dùng để Fastlane có quyền upload lên Firebase
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: bundle exec fastlane distribute_to_qa