name: Distribute to Firebase QA

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      # 1. Lấy code về
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Cài đặt Java (Cần thiết để build Android)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Cài đặt Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3.1 Cài Git và curl (yêu cầu bắt buộc cho shorebird)
      - name: Setup Git and dependencies
        run: sudo apt-get update && sudo apt-get install -y git curl

      # 3.2 Cài đặt Shorebird CLI (clone trực tiếp)
      - name: Install Shorebird
        run: |
          git clone https://github.com/shorebirdtech/shorebird.git -b stable /home/runner/.config/shorebird
          /home/runner/.config/shorebird/bin/shorebird --version
        env:
          PATH: /home/runner/.config/shorebird/bin:$PATH
      # ========================================================
      # BƯỚC QUAN TRỌNG: TẠO FILE GOOGLE-SERVICES TỪ SECRET
      # ========================================================
      - name: 📝 Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json

      # 4. Cài đặt Ruby & Tự động chạy Bundle Install cho Fastlane
      - name: Setup Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: android

      # 5. Kích hoạt Fastlane
      - name: Build and Distribute APK
        working-directory: android
        env:
          # Token này dùng để Fastlane có quyền upload lên Firebase
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: bundle exec fastlane distribute_to_qa